"""Generate js/galleries.js from each project's manifest.json.
Run after downloading new images. Output sets window.GALLERIES.
"""
import os, json, re

ROOT = "assets/images/projects"
# section display order priority (lower = earlier)
ORDER = {"wireframes": 0, "figma wireframes": 0, "mockups": 1, "screens": 1,
         "flowcharts": 2, "bpmn diagrams": 3, "use case diagrams": 4,
         "diagrams": 5, "er diagrams": 6}

def singular(label):
    base = re.sub(r"s$", "", label.strip())
    return base

out = {}
for slug in sorted(os.listdir(ROOT)):
    d = os.path.join(ROOT, slug)
    man = os.path.join(d, "manifest.json")
    if not os.path.isdir(d) or not os.path.exists(man):
        continue
    groups = json.load(open(man, encoding="utf-8"))
    groups.sort(key=lambda g: ORDER.get(g["label"].lower(), 9))
    glist = []
    for g in groups:
        label = g["label"]
        files = g["files"]
        caps = g.get("captions", [])
        images = []
        for i, f in enumerate(files):
            cap = caps[i] if i < len(caps) else f"{singular(label)} {i+1}"
            images.append({"src": f"{ROOT}/{slug}/{f}", "caption": cap})
        glist.append({"label": label, "images": images})
    out[slug] = glist

js = "/* AUTO-GENERATED by _dl/gen_galleries.py — do not edit by hand. */\n"
js += "window.GALLERIES = " + json.dumps(out, indent=2) + ";\n"
open("js/galleries.js", "w", encoding="utf-8").write(js)

print("Wrote js/galleries.js")
for slug, gl in out.items():
    print(f"  {slug:20} " + ", ".join(f"{g['label']}({len(g['images'])})" for g in gl))
